### ISSUE TITLE
Fix comma color on multiple elements

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/reVolt#109]
When there are 2 or more elements specified for a rune, it has commas added, which are for some reason blue. Need to change them to white.

Opened from Discord by **Shush#1242**
Follow the conversation [here](https://discord.com/channels/501306949434867713/826466764606799882/848557385793667115)

**Comment by Shushishtok** [comment]
Fixed in https://github.com/arcadia-redux/reVolt/pull/103
