### ISSUE TITLE
Add -dev commands

### ISSUE THREAD

**Issue by Shushishtok** [arcadia-redux/reVolt#15]
Add dev commands for debugging.
Dev commands should only work in tools mode or in cheat mode.

Commands:
`-startround <round number>` - starts a new round for all players with the current wave set to `<round number>`. If a new round is currently ongoing, end the round by killing all remaining units. 
Example usages:
* `-startround 5`

`-endround` - ends the current round for all players by killing all remaining units. 
Example usages:
* `-endround`

`-addweapon <weapon name> <playerID> | all` - Adds the weapon named `<weapon name>` to the inventory of the player which has player ID `<playerID>`. Defaults to player ID 0 if `<playerID>` is omitted.  If all is used instead of a player ID, all players get a copy of the weapon.
Example usages: 
* `-addweapon basic_chaos` -> adds the basic_chaos weapon to player ID 0.
* `-addweapon basic_chaos 3` -> adds the basic_chaos weapon to player ID 3.
* `-addweapon basic_chaos all` -> adds the basic_chaos weapon to all players.

-`removeweapon <weapon name> <playerID> | all` - Removes one instance of the weapon named `<weapon name>` from the inventory of the player which has player ID `<playerID>`. Defaults to player ID 0 if `<playerID>` is omitted. If all is used instead of a player ID, all players have one copy of the weapon, if any, removed from their inventory. Does not removes equipped weapons (need to unequip them first).
Example usages:
* `-removeweapon basic_chaos` -> removes one instance of the basic_chaos weapon from player ID 0, if any. Ignores equipped instances.
* `-removeweapon basic_chaos 3` -> removes one instance of the basic_chaos weapon from player ID 3, if any. Ignores equipped instances.
* `-removeweapon basic_chaos all` -> removes one instance of the basic_chaos weapon from all players, if any. Ignores equipped instances.

`-shufflepresets` - Fetches a new set of presets for all players. Only works when presets are shown.
Example usages:
* `-shufflepresets`

`-shuffleshopitems` - Fetches a new set of shop items (to be done after shops are implemented).
Example usages:
* `-shuffleshopitems`

`-setlives <number of lives> <playerID> | all` - sets the number of lives of a player which has player ID `<playerID>` to `<number of lives>`. Defaults to player ID 0 if `<playerID>` is omitted. Must be a positive integer. If all is used instead of a player ID, all players have their lives set to this amount. (to be done after lives are implemented)
Example usages:
* `-setlives 3` -> sets lives of playerID 0 to 3.
* `-setlives 3 2` -> sets lives of playerID 2 to 3.
* `-setlives 3 all` -> set lives of all players to 3.

Additional dev commands may be added in the future to this list.

**Comment by Shushishtok** [comment]
Also, adding the above functionalities mean that we can remove the hero's abilities that adds and removes a weapon.

**Comment by Nibuja05** [comment]
Maybe we should/could also make a dev panorama panel for that stuff as an addition?
Like in the chc demo mode.

**Comment by Shushishtok** [comment]
For sure, that sounds even better.

**Comment by Nibuja05** [comment]
Out of necessity, following dev commands got added:

- `addshards <number of shards> <playerID> | all` - add one shard of every type for a player.
- `addgold <amount of gold> <playerID> | all` - adds gold for a player.

**Comment by Shushishtok** [comment]
The only missing one is Shuffle Presets, which I think is not really necessary.
All others are implemented as of https://github.com/arcadia-redux/reVolt/pull/87
