### ISSUE TITLE
Close shop automatically.

### ISSUE THREAD

**Issue by Nibuja05** [arcadia-redux/reVolt#36]
Close shop with similar rules to Dota: when clicking outside of the shop or when pressing ESC while the shop has focus.

**Comment by Shushishtok** [comment]
For an example on the mouse clicks outside UI to close the window:
https://github.com/Shushishtok/dota-reimagined/blob/master/content/panorama/scripts/custom_game/talent_windows.ts#L758-L787

You don't need the currentUnit check.

For pressing ESC:
https://github.com/Shushishtok/dota-reimagined/blob/master/content/panorama/scripts/custom_game/talent_windows.ts#L749-L755

**Comment by Nibuja05** [comment]
Last PR should have closed this.
