### ISSUE TITLE
Add gold gain

### ISSUE THREAD

**Issue by Nibuja05** [arcadia-redux/reVolt#46]
Enemies should drop gold. Either randomly or a fixed amount.
Should be equal or almost equal emong all players.

**Comment by Shushishtok** [comment]
Removed the need concept since we have a concept defined.

@Nibuja05 Didn't you implement gold gain from enemies in #63 ?

**Comment by Nibuja05** [comment]
since it closed multiple issues I forgot this one. Can be closed.
