### ISSUE TITLE
Refresh market offers for all players on wave complete

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/reVolt#75]
Currently the offers don't refresh after a completed round. This is caused, because currently there is no event, that is called when ALL players finished their round. This should be implemented after finishing #18.

Opened from Discord by **Nibuja#6654**
Follow the conversation [here](https://discord.com/channels/501306949434867713/826466764606799882/840665427407536149)

**Comment by Nibuja05** [comment]
Already fixed in a previous [PR](https://github.com/arcadia-redux/reVolt/pull/80)
