### ISSUE TITLE
Implement coolup mechanics

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/reVolt#88]
Make a utility function to implement coolup, which is a cooldown a unit has before it can cast the ability for the first time when it spawns.

Opened from Discord by **Shush#1242**
Follow the conversation [here](https://discord.com/channels/501306949434867713/826466764606799882/843170318502723624)

**Comment by Shushishtok** [comment]
Done in https://github.com/arcadia-redux/reVolt/pull/92
