### ISSUE TITLE
Implement move speed changes on players

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/reVolt#89]
Currently, since the move speed is done via absolute speeds, the hero ignores standard move speed buffs or slows. A custom function should be added that the absolute speed takes into account when calculating the absolute speed to go by.

Opened from Discord by **Shush#1242**
Follow the conversation [here](https://discord.com/channels/501306949434867713/826466764606799882/843171676535128125)

**Comment by Shushishtok** [comment]
Already fixed in https://github.com/arcadia-redux/reVolt/pull/95. Can be closed.
