### ISSUE TITLE
Change absorb bar to be vertical

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/reVolt#90]
Currently, the absorb bar is on the right, and its height changes based on the height of the tooltips. In order to be more consistent, the bar should be vertical, and should be placed below the title, above the description (description would be pushed down slightly).

Opened from Discord by **Shush#1242**
Follow the conversation [here](https://discord.com/channels/501306949434867713/826466764606799882/843176304287547442)

**Comment by Shushishtok** [comment]
Done by @Nibuja05 in https://github.com/arcadia-redux/reVolt/pull/87
